# Generated by Django 5.2 on 2025-09-15 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppAdmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email del usuario que realizó la acción', max_length=254)),
                ('action', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('inactivar', 'Inactivar'), ('activar', 'Activar')], help_text='Acción realizada', max_length=20)),
                ('action_datetime', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la acción')),
                ('affected_type', models.CharField(choices=[('ubicacion', 'Ubicación'), ('sistema', 'Sistema')], help_text='Tipo de registro afectado', max_length=20)),
                ('affected_value', models.CharField(help_text='Valor del registro afectado', max_length=255)),
                ('affected_id', models.PositiveIntegerField(help_text='ID del registro afectado')),
                ('ip_address', models.CharField(help_text='Dirección IP del usuario', max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acción de Usuario',
                'verbose_name_plural': 'Logs de Acciones de Usuarios',
                'ordering': ['-action_datetime'],
                'indexes': [models.Index(fields=['email'], name='DAppAdmin_u_email_335d2e_idx'), models.Index(fields=['action_datetime'], name='DAppAdmin_u_action__5fc591_idx'), models.Index(fields=['user'], name='DAppAdmin_u_user_id_d93436_idx'), models.Index(fields=['affected_type'], name='DAppAdmin_u_affecte_10853d_idx'), models.Index(fields=['action'], name='DAppAdmin_u_action_33349d_idx')],
            },
        ),
    ]
