# Generated by Django 5.2 on 2025-09-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppAdmin', '0002_useractionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='affected_id',
            field=models.CharField(help_text='ID del registro afectado', max_length=50),
        ),
    ]
