# Generated by Django 5.2 on 2025-09-15 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppAdmin', '0003_alter_useractionlog_affected_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='affected_id',
            field=models.UUIDField(help_text='ID del registro afectado'),
        ),
    ]
