# Generated by Django 5.2 on 2025-09-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppAdmin', '0004_useractionlog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='affected_id',
            field=models.CharField(help_text='ID del registro afectado', max_length=255),
        ),
        migrations.AlterField(
            model_name='useractionlog',
            name='affected_type',
            field=models.CharField(choices=[('ubicacion', 'Ubicación'), ('sistema', 'Sistema'), ('usuario', 'Usuario')], help_text='Tipo de registro afectado', max_length=20),
        ),
    ]
