# Generated by Django 5.2 on 2025-09-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_AppAdmin', '0005_alter_useractionlog_affected_id_and_more'),
    ]

    operations = [
    ]
