# Generated by Django 5.2 on 2025-11-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppAdmin', '0006_auto_20250916_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='affected_value',
            field=models.CharField(help_text='Valor del registro afectado', max_length=2000),
        ),
    ]
