# Generated by Django 5.2 on 2025-09-12 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email del usuario que hizo login', max_length=254)),
                ('login_datetime', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del login')),
                ('ip_address', models.CharField(help_text='Dirección IP del usuario', max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Login',
                'verbose_name_plural': 'Logs de Login',
                'ordering': ['-login_datetime'],
                'indexes': [models.Index(fields=['email'], name='DAppAuth_us_email_f09953_idx'), models.Index(fields=['login_datetime'], name='DAppAuth_us_login_d_713342_idx'), models.Index(fields=['user'], name='DAppAuth_us_user_id_6e5586_idx')],
            },
        ),
    ]
