# Generated by Django 5.2 on 2025-09-16 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación'),
        ),
    ]
