# Generated by Django 5.2 on 2025-09-16 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('_AppAuth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Solo crear el nuevo modelo con BaseModel (sin eliminar el anterior)
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(help_text='Email del usuario que hizo login', max_length=254)),
                ('login_datetime', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del login')),
                ('ip_address', models.CharField(help_text='Dirección IP del usuario', max_length=45)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Login',
                'verbose_name_plural': 'Logs de Login',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['email'], name='_AppAuth_us_email_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['created_at'], name='_AppAuth_us_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginlog',
            index=models.Index(fields=['user'], name='_AppAuth_us_user_idx'),
        ),
    ]
