# Generated by Django 5.2 on 2025-09-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_AppAuth', '0002_auto_20250916_0931'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userloginlog',
            new_name='DAppAuth_us_email_f09953_idx',
            old_name='_AppAuth_us_email_idx',
        ),
        migrations.RenameIndex(
            model_name='userloginlog',
            new_name='DAppAuth_us_created_449586_idx',
            old_name='_AppAuth_us_created_idx',
        ),
        migrations.RenameIndex(
            model_name='userloginlog',
            new_name='DAppAuth_us_user_id_6e5586_idx',
            old_name='_AppAuth_us_user_idx',
        ),
    ]
