# Generated by Django 5.2 on 2025-09-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_AppHome', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipo',
        ),
    ]
