from .CreateTecnologiaCommand.CreateTecnologiaCommand import crearTecnologia
from .UpdateTecnologiaCommand.UpdateTecnologiaCommand import EditarTecnologiaView
from .DeleteTecnologiaCommand.DeleteTecnologiaCommand import DeleteTecnologiaCommand
