from .GetAllTipoCriticidadPagQuery.GetAllTipoCriticidadPagQuery import TipoCriticidadPaginatedAPI
from ..views_template import TipoCriticidadPaginatedHTML
from .GetAllTipoCriticidadListQuery import GetAllTipoCriticidadListQuery