# Generated by Django 5.2 on 2025-09-22 14:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeRedData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag_system', models.CharField(blank=True, max_length=100, null=True)),
                ('total_volume', models.FloatField(blank=True, null=True)),
                ('forward_volume', models.FloatField(blank=True, null=True)),
                ('reverse_volume', models.FloatField(blank=True, null=True)),
                ('total_mass', models.FloatField(blank=True, null=True)),
                ('forward_mass', models.FloatField(blank=True, null=True)),
                ('reverse_mass', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('volume_60f', models.FloatField(blank=True, null=True)),
                ('specific_gravity_60f', models.FloatField(blank=True, null=True)),
                ('flow_rate', models.FloatField(blank=True, null=True)),
                ('mass_rate', models.FloatField(blank=True, null=True)),
                ('coriolis_temperature', models.FloatField(blank=True, null=True)),
                ('diagnostic_temperature', models.FloatField(blank=True, null=True)),
                ('redundant_temperature', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
