# Generated by Django 5.2 on 2025-07-17 20:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeRedData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
