# Generated by Django 5.2 on 2025-09-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppMonitoreoCoriolis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodereddata',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='nodereddata',
            name='valor',
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='caudal_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='densidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='grav_spec_60f',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='masa_fwd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='masa_rev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='masa_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='mass_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='presion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='tag_Sistema',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='temperatura_coriolis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='temperatura_diagnostico',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='temperatura_redundante',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='volumen_60f',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='volumen_fwd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='volumen_rev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='volumen_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
