# Generated by Django 5.2 on 2025-09-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_AppMonitoreoCoriolis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodereddata',
            old_name='tag_system',
            new_name='mac_gateway',
        ),
    ]
