# Generated by Django 5.2 on 2025-09-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_AppMonitoreoCoriolis', '0002_remove_nodereddata_sensor_remove_nodereddata_valor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodereddata',
            old_name='tag_Sistema',
            new_name='tag_system',
        ),
        migrations.RenameField(
            model_name='nodereddata',
            old_name='volumen_total',
            new_name='total_volume',
        ),
        migrations.RenameField(
            model_name='nodereddata',
            old_name='volumen_fwd',
            new_name='forward_volume',
        ),
        migrations.RenameField(
            model_name='nodereddata',
            old_name='volumen_rev',
            new_name='reverse_volume',
        ),
        migrations.RenameField(
            model_name='nodereddata',
            old_name='masa_total',
            new_name='total_mass',
        ),
        migrations.RenameField(
            model_name='nodereddata',
            old_name='masa_fwd',
            new_name='forward_mass',
        ),
        migrations.RenameField(
            model_name='nodereddata',
            old_name='masa_rev',
            new_name='reverse_mass',
        ),
        migrations.RenameField(
            model_name='nodereddata',
            old_name='densidad',
            new_name='density',
        ),
        migrations.RenameField(
            model_name='nodereddata',
            old_name='volumen_60f',
            new_name='volume_60f',
        ),
        migrations.RenameField(
            model_name='nodereddata',
            old_name='grav_spec_60f',
            new_name='specific_gravity_60f',
        ),
        migrations.RenameField(
            model_name='nodereddata',
            old_name='caudal_rate',
            new_name='flow_rate',
        ),
        migrations.RenameField(
            model_name='nodereddata',
            old_name='temperatura_coriolis',
            new_name='coriolis_temperature',
        ),
        migrations.RenameField(
            model_name='nodereddata',
            old_name='temperatura_diagnostico',
            new_name='diagnostic_temperature',
        ),
        migrations.RenameField(
            model_name='nodereddata',
            old_name='temperatura_redundante',
            new_name='redundant_temperature',
        ),
        migrations.RenameField(
            model_name='nodereddata',
            old_name='presion',
            new_name='pressure',
        ),
    ]
