# Generated by Django 5.2 on 2025-09-23 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppComplementos', '0006_auto_20250916_0833'),
        ('_AppMonitoreoCoriolis', '0002_rename_tag_system_nodereddata_mac_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodereddata',
            name='conc_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='conc_rate_alm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='coriolis_frecuency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='coriolis_frecuency_alm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='coriolis_temperature_alm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='density_alm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='diagnostic_temperature_alm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='driver_curr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='driver_curr_alm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='dsp_rxmsg_amplitudeEstimateA1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='dsp_rxmsg_amplitudeEstimateA2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='dsp_rxmsg_driverAmplitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='dsp_rxmsg_noiseEstimatedN1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='dsp_rxmsg_noiseEstimatedN2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='forward_conc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='forward_productionWater',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='mass_rate_alm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='pconc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='pconc_alm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='percent_cutWater16b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='percent_cutWater64b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='percent_cutWater_alm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='productionWater_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='productionWater_rate_alm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='reverse_conc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='reverse_productionWater',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='signal_strength_rxCoriolis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='systemId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nodered_data', to='_AppComplementos.sistema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='temperature_gateway',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='total_conc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='total_productionWater',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='vol_rate_alm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
