# Generated by Django 5.2 on 2025-09-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppMonitoreoCoriolis', '0003_nodereddata_conc_rate_nodereddata_conc_rate_alm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodereddata',
            old_name='pressure',
            new_name='pressure_in',
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='pressure_out',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
