# Generated by Django 5.2 on 2025-10-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppMonitoreoCoriolis', '0004_rename_pressure_nodereddata_pressure_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodereddata',
            name='bp',
            field=models.FloatField(blank=True, help_text='Coeficiente B para presión vigente al momento del registro', null=True, verbose_name='B Presión'),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='bt',
            field=models.FloatField(blank=True, help_text='Coeficiente B para temperatura de salida vigente al momento del registro', null=True, verbose_name='B Temperatura'),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='mp',
            field=models.FloatField(blank=True, help_text='Coeficiente M para presión vigente al momento del registro', null=True, verbose_name='M Presión'),
        ),
        migrations.AddField(
            model_name='nodereddata',
            name='mt',
            field=models.FloatField(blank=True, help_text='Coeficiente M para temperatura de salida vigente al momento del registro', null=True, verbose_name='M Temperatura'),
        ),
    ]
