# Generated by Django 5.2 on 2025-10-07 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppComplementos', '0010_configuracioncoeficientes_span_presion_and_more'),
        ('_AppMonitoreoCoriolis', '0005_nodereddata_bp_nodereddata_bt_nodereddata_mp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchDetectado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio del Batch')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de Fin del Batch')),
                ('vol_total', models.FloatField(verbose_name='Volumen Total Acumulado (kg)')),
                ('temperatura_coriolis_prom', models.FloatField(verbose_name='Temperatura Coriolis Promedio (°C)')),
                ('densidad_prom', models.FloatField(verbose_name='Densidad Promedio (g/cc)')),
                ('duracion_minutos', models.FloatField(blank=True, null=True, verbose_name='Duración del Batch (minutos)')),
                ('total_registros', models.IntegerField(default=0, verbose_name='Total de Registros en el Batch')),
                ('systemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches_detectados', to='_AppComplementos.sistema')),
            ],
            options={
                'verbose_name': 'Batch Detectado',
                'verbose_name_plural': 'Batches Detectados',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
