# Generated by Django 5.2 on 2025-10-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppMonitoreoCoriolis', '0006_batchdetectado'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodereddata',
            name='created_at_iot',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora del IoT'),
        ),
    ]
