# Generated by Django 5.2 on 2025-10-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppMonitoreoCoriolis', '0007_nodereddata_created_at_iot'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdetectado',
            name='hash_identificacion',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='Hash de Identificación'),
        ),
    ]
