# Generated by Django 5.2 on 2025-10-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppMonitoreoCoriolis', '0008_batchdetectado_hash_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdetectado',
            name='perfil_lim_inf_caudal',
            field=models.FloatField(blank=True, null=True, verbose_name='Límite Inferior Caudal del Perfil (kg/h)'),
        ),
        migrations.AddField(
            model_name='batchdetectado',
            name='perfil_lim_sup_caudal',
            field=models.FloatField(blank=True, null=True, verbose_name='Límite Superior Caudal del Perfil (kg/h)'),
        ),
        migrations.AddField(
            model_name='batchdetectado',
            name='perfil_vol_minimo',
            field=models.FloatField(blank=True, null=True, verbose_name='Volumen Mínimo del Perfil (kg)'),
        ),
    ]
