# Generated by Django 5.2 on 2025-10-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppMonitoreoCoriolis', '0009_batchdetectado_perfil_lim_inf_caudal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdetectado',
            name='num_ticket',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Ticket asignado'),
        ),
    ]
