# Generated by Django 5.2 on 2025-10-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppMonitoreoCoriolis', '0010_batchdetectado_num_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdetectado',
            name='mass_total',
            field=models.FloatField(default=0.0, verbose_name='Masa Total Acumulada (kg)'),
        ),
        migrations.AlterField(
            model_name='batchdetectado',
            name='vol_total',
            field=models.FloatField(verbose_name='Volumen Total Acumulado (m³)'),
        ),
    ]
