# Generated by Django 5.2 on 2025-10-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppMonitoreoCoriolis', '0011_batchdetectado_mass_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdetectado',
            name='pressure_out_prom',
            field=models.FloatField(blank=True, null=True, verbose_name='Presión de Salida Promedio (PSI)'),
        ),
    ]
