# Generated by Django 5.2 on 2025-10-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppMonitoreoCoriolis', '0012_batchdetectado_pressure_out_prom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdetectado',
            name='vol_total',
            field=models.FloatField(verbose_name='Volumen Total Acumulado (gal)'),
        ),
    ]
