# Generated by Django 5.2 on 2025-10-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppMonitoreoCoriolis', '0013_alter_batchdetectado_vol_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdetectado',
            name='time_finished_batch',
            field=models.FloatField(blank=True, null=True, verbose_name='Tiempo de Cierre de Batch usado (minutos)'),
        ),
    ]
