# Generated by Django 5.2 on 2025-11-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_AppMonitoreoCoriolis', '0014_batchdetectado_time_finished_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodereddata',
            old_name='specific_gravity_60f',
            new_name='time_closed_batch',
        ),
        migrations.RenameField(
            model_name='nodereddata',
            old_name='volume_60f',
            new_name='vol_detect_batch',
        ),
    ]
