# Generated by Django 5.2 on 2025-12-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppMonitoreoCoriolis', '0015_rename_specific_gravity_60f_nodereddata_time_closed_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdetectado',
            name='num_ticket',
            field=models.CharField(blank=True, help_text='Formato automático: {ubicacion}-{YYYYMMDD}-{HHMMSS}', max_length=50, null=True, unique=True, verbose_name='Número de Ticket asignado'),
        ),
    ]
