# Generated by Django 5.2 on 2026-01-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppMonitoreoCoriolis', '0015_rename_specific_gravity_60f_nodereddata_time_closed_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdetectado',
            name='num_ticket',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Ticket asignado (AAMMDD_#)'),
        ),
    ]
