# Generated by Django 5.1.6 on 2025-04-07 21:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criticidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Criticidad',
                'verbose_name_plural': 'Criticidades',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='TipoCriticidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Criticidad',
                'verbose_name_plural': 'Tipos de Criticidad',
            },
        ),
        migrations.CreateModel(
            name='TipoCriticidadCriticidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criticidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_AppComplementos.criticidad')),
                ('tipo_criticidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_AppComplementos.tipocriticidad')),
            ],
            options={
                'unique_together': {('tipo_criticidad', 'criticidad')},
            },
        ),
        migrations.CreateModel(
            name='ProductoTipoCritCrit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_AppComplementos.producto')),
                ('relacion_tipo_criticidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_AppComplementos.tipocriticidadcriticidad')),
            ],
            options={
                'unique_together': {('producto', 'relacion_tipo_criticidad')},
            },
        ),
    ]
