# Generated by Django 5.1.6 on 2025-03-14 18:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppComplementos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCriticidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('criticidades', models.ManyToManyField(related_name='tipos_criticidad', to='_AppComplementos.criticidad')),
            ],
            options={
                'verbose_name': 'Tipo de Criticidad',
                'verbose_name_plural': 'Tipos de Criticidad',
            },
        ),
    ]
