# Generated by Django 5.2 on 2025-07-07 18:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppComplementos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipo',
            },
        ),
        migrations.AlterField(
            model_name='productotipocritcrit',
            name='relacion_tipo_criticidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='_AppComplementos.tipocriticidadcriticidad'),
        ),
        migrations.AlterField(
            model_name='tipocriticidadcriticidad',
            name='criticidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_criticidad_relaciones', to='_AppComplementos.criticidad'),
        ),
        migrations.CreateModel(
            name='TipoEquipoProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relacion_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_equipo', to='_AppComplementos.productotipocritcrit')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_AppComplementos.tipoequipo')),
            ],
            options={
                'unique_together': {('tipo_equipo', 'relacion_producto')},
            },
        ),
    ]
