# Generated by Django 5.2 on 2025-07-08 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppComplementos', '0002_tipoequipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
            },
        ),
        migrations.CreateModel(
            name='TecnologiaTipoEquipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relacion_tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnologias', to='_AppComplementos.tipoequipoproducto')),
                ('tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_AppComplementos.tecnologia')),
            ],
            options={
                'unique_together': {('tecnologia', 'relacion_tipo_equipo')},
            },
        ),
    ]
