# Generated by Django 5.2 on 2025-07-14 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppComplementos', '0003_tecnologia_tecnologiatipoequipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Ubicación')),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitud')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
    ]
