# Generated by Django 5.2 on 2025-07-14 16:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppComplementos', '0004_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(max_length=50, verbose_name='Tag')),
                ('sistema_id', models.CharField(max_length=50, verbose_name='ID Sistema')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas', to='_AppComplementos.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
                'unique_together': {('tag', 'sistema_id', 'ubicacion')},
            },
        ),
    ]
