# Generated by Django 5.2 on 2025-09-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_AppComplementos', '0005_sistema'),
    ]

    operations = [
        # Eliminar modelos de relación primero
        migrations.DeleteModel(
            name='TipoCriticidadCriticidad',
        ),
        migrations.DeleteModel(
            name='ProductoTipoCritCrit',
        ),
        migrations.DeleteModel(
            name='TipoEquipoProducto',
        ),
        migrations.DeleteModel(
            name='TecnologiaTipoEquipo',
        ),
        # Eliminar modelos principales
        migrations.DeleteModel(
            name='Criticidad',
        ),
        migrations.DeleteModel(
            name='TipoCriticidad',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='TipoEquipo',
        ),
        migrations.DeleteModel(
            name='Tecnologia',
        ),
    ]
