# Generated by Django 5.2 on 2025-09-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppComplementos', '0006_auto_20250916_0833'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sistema',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='sistema_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID Sistema'),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='tag',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tag'),
        ),
    ]
