# Generated by Django 5.2 on 2025-10-02 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppComplementos', '0007_alter_sistema_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCoeficientes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mt', models.FloatField(verbose_name='M Temperatura')),
                ('bt', models.FloatField(verbose_name='B Temperatura')),
                ('mp', models.FloatField(verbose_name='M Presión')),
                ('bp', models.FloatField(verbose_name='B Presión')),
                ('systemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coeficientes', to='_AppComplementos.sistema', verbose_name='Sistema')),
            ],
            options={
                'verbose_name': 'Configuración de Coeficientes',
                'verbose_name_plural': 'Configuraciones de Coeficientes',
                'unique_together': {('systemId',)},
            },
        ),
    ]
