# Generated by Django 5.2 on 2025-10-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppComplementos', '0008_configuracioncoeficientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='lim_inf_caudal_masico',
            field=models.FloatField(default=0.0, verbose_name='Límite Inferior Caudal Másico'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='lim_sup_caudal_masico',
            field=models.FloatField(default=1000000.0, verbose_name='Límite Superior Caudal Másico'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='vol_masico_ini_batch',
            field=models.FloatField(default=0.0, verbose_name='Volumen Másico Total para confirmación de bath'),
        ),
    ]
