# Generated by Django 5.2 on 2025-10-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppComplementos', '0009_configuracioncoeficientes_lim_inf_caudal_masico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='span_presion',
            field=models.FloatField(default=1.0, verbose_name='Span Presión'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='zero_presion',
            field=models.FloatField(default=0.0, verbose_name='Zero Presión'),
        ),
    ]
