# Generated by Django 5.2 on 2025-10-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppComplementos', '0010_configuracioncoeficientes_span_presion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='num_ticket',
            field=models.IntegerField(default=1, verbose_name='Número de Ticket'),
        ),
    ]
