# Generated by Django 5.2 on 2025-10-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppComplementos', '0011_configuracioncoeficientes_num_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='identificacion_medidor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Identificación del Medidor'),
        ),
    ]
