# Generated by Django 5.2 on 2025-10-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppComplementos', '0012_sistema_identificacion_medidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='time_finished_batch',
            field=models.FloatField(default=2.0, help_text='Minutos que deben pasar en cero para confirmar cierre de batch', verbose_name='Tiempo de espera para cierre de batch (minutos)'),
        ),
    ]
