# Generated by Django 5.2 on 2025-11-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_AppComplementos', '0013_configuracioncoeficientes_time_finished_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='deltavis',
            field=models.FloatField(blank=True, null=True, verbose_name='Rango viscosidad (cP)'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='desv_dens',
            field=models.FloatField(blank=True, null=True, verbose_name='Desviación viscosidad (kg/m³)'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='dl',
            field=models.FloatField(blank=True, null=True, verbose_name='Densidad (kg/m³)'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='dn',
            field=models.FloatField(blank=True, null=True, verbose_name='Diámetro nominal (in)'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='esis_met',
            field=models.FloatField(blank=True, null=True, verbose_name='Error máximo medidor (%)'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='kcal_dens',
            field=models.FloatField(blank=True, null=True, verbose_name='Factor de cobertura densitómetro (-)'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='kcal_met',
            field=models.FloatField(blank=True, null=True, verbose_name='Factor de cobertura medidor'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='masa',
            field=models.FloatField(blank=True, null=True, verbose_name='Masa indicada por el medidor (kg)'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='metdl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Método de análisis densidad'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='mf',
            field=models.FloatField(blank=True, null=True, verbose_name='Factor de corrección del medidor (-)'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='pl',
            field=models.FloatField(blank=True, null=True, verbose_name='Presión de líquido promedio (psi)'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='product',
            field=models.CharField(default='GLP', max_length=50, verbose_name='Tipo de fluido'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='qm',
            field=models.FloatField(blank=True, null=True, verbose_name='Caudal másico promedio (kg/h)'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='tipdens',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de densitómetro'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='tipo_met',
            field=models.CharField(default='Coriolis', max_length=50, verbose_name='Tipo de medidor'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='tl',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura de líquido promedio (°F)'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='ucal_dens',
            field=models.FloatField(blank=True, null=True, verbose_name='Incertidumbre calibración densitómetro (kg/m³)'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='ucal_met',
            field=models.FloatField(blank=True, null=True, verbose_name='Incertidumbre calibración medidor (%)'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='ucarta_met',
            field=models.FloatField(blank=True, null=True, verbose_name='Incertidumbre carta medidor (%)'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='vis',
            field=models.FloatField(blank=True, null=True, verbose_name='Viscosidad dinámica (cP)'),
        ),
        migrations.AddField(
            model_name='configuracioncoeficientes',
            name='zero_stab',
            field=models.FloatField(blank=True, null=True, verbose_name='Estabilidad en cero medidor (Kg/m³)'),
        ),
    ]
