from .GetAllCriticidadPagQuery import GetAllCriticidadPagQuery
from .GetAllCriticidadListQuery import GetAllCriticidadListQuery
from .GetCriticidadPorTipoCritQuery import GetCriticidadPorTipoCritQuery