from .GetAllCriticidadPagQuery import CriticidadPaginatedAPI, CriticidadPaginatedHTML
from .GetAllCriticidadListQuery import GetAllCriticidadListQuery
from .GetCriticidadPorTipoCritQuery import GetCriticidadPorTipoCritQuery